name: Treinando Modelos
on:

  schedule:
    - cron: "* * 2 * *"
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Copia os arquivos do repo
          uses: actions/checkout@v4
        - name: Instalar o Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Cache Python dependencies
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install dependencies
          run: |
            make install
        - name: Coleta de Dados
          run: |
            cd ./codigos_rodando
            pwd
            python rodando_treinamento.py
        - name: Configure Git
          run: |
            git config --global user.email "sehnemjeferson@gmail.com"
            git config --global user.name "Jeferson Sehnem"
        - name: Commit and push changes
          run: |
            git add .
            git commit -m "Update data: $(date +'%Y-%m-%d')"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.ACTIONS_PREDICOES }}